blog/urls.py
from django.contrib import admin
from django.urls import path, include

from blog.views import postDetail, allPosts, postShare, postComment

app_name = 'blog'

urlpatterns = [
    # path('', ),
    path('all_posts', allPosts, name='all-posts'),
    path('tag/<slug:tag_slug>/', allPosts, name='all-posts-with-tag' ),
    # path('all_posts', PostsList.as_view(), name='all-posts'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', postDetail,
         name='post-detail'),
    path('<int:post_id>/share/', postShare, name='post-share'),
    path('<int:post_id>/comment/', postComment, name='post-comment'),
]

realstateofmind/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

from taggit.managers import TaggableManager

# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLIC)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLIC = 'PB', 'Public'

    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_post')
    tags=TaggableManager()
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publictiondate')
    content = models.TextField(max_length=3000)
    publictiondate = models.DateTimeField(default=timezone.now)
    creationeddate = models.DateTimeField(auto_now_add=True)
    updateddate = models.DateTimeField(auto_now=True)
    visible = models.BooleanField(default=1)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    object = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['publictiondate']
        indexes = [models.Index(fields=['publictiondate'])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post-detail",
                       args=[self.publictiondate.year,
                             self.publictiondate.month,
                             self.publictiondate.day, self.slug])


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    email = models.EmailField()
    cmnt_txt = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created']), ]

    def __str__(self):
        return f"Comment from {self.email} for post '{self.post.title}'"

shop/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms

from blog.models import PostComment


class EmailPostForm(forms.Form):
    sender_name = forms.CharField(max_length=30)
    sender_email = forms.EmailField()
    recipient_email = forms.EmailField()
    message = forms.CharField(required=False, widget=forms.Textarea)


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ['email', 'email', 'cmnt_txt']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from blog.forms import EmailPostForm, PostCommentForm
from blog.models import Post


# Create your views here.


def allPosts(request, tag_slug=None):
    posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)

    try:
        posts_pages = paginator.page(page_number)
    except PageNotAnInteger:
        posts_pages = paginator.page(1)
    except EmptyPage:
        # return last page (num of page = last)
        posts_pages = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/posts/all-posts.html',
                  {'posts': posts_pages, 'tag': tag})


# class PostsList(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 2
#     template_name = 'blog/posts/all-posts.html'

def postDetail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLIC,
                             slug=post,
                             publictiondate__year=year,
                             publictiondate__month=month,
                             publictiondate__day=day)
    comments = post.comments.filter(active=True)
    form = PostCommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
        id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by(
        '-same_tags', '-publictiondate')[:4]

    return render(request, 'blog/posts/post-detail.html',
                  {'post': post, 'comments': comments, 'form': form,
                   'similar_posts': similar_posts})


def postShare(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLIC)
    sent = False

    if request.method == 'GET':
        form = EmailPostForm(request.GET)
        return render(request,
                      'blog/posts/post-share.html',
                      {'post': post, 'form': form, 'sent': sent})

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["sender_name"]} send to you post {post.title} '
            msn = f"Read '{post.title}' link to {post_url}"
            send_mail(subject, msn, 'mymail@gm.com',
                      [cd['recipient_email']])
            sent = True
        else:
            form = EmailPostForm()
        return render(request,
                      'blog/posts/post-share.html',
                      {'post': post, 'form': form, 'sent': sent})


def postComment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLIC)
    comment = None
    form = PostCommentForm(data=request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/posts/form-post-comment.html',
                  {'post': post, 'form': form, 'comment': comment})

shop/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/posts/all-posts.html
{% extends "layout.html" %}
{% load blog_tags %}


{% block title %}blooog{% endblock title %}

{% block content %}

    <h1>My blog</h1>

    <div style="color: green;">
        <h3>Latest posts</h3>
        {% show_latest_published_posts 2 %}
    </div>

    <div style="color: green;">
        <h3>Most commented posts</h3>
        {% most_commented_published_posts as mmp %}
        <ul>
            {% for post in mmp %}
                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    </div>



 
    </div>


    {% if tag %}
        <h2>Posty oznaczone tagiem {{ tag.name }} </h2>
    {% endif %}
    {% for post in posts %}
        <a href="{{ post.get_absolute_url }}"><h4 style="background-color: lightgreen;">{{ post.title }}</h4></a>
        {% if post.tags.all %}            
        <p>Tags: #{{ post.tags.all|join:" #" }}</p>        
    {% endif %}


    <div>
        <h2 style="color: red;">Post: '{{ post.title }}'</h2>
            <p>Tagi:
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:all-posts-with-tag' tag.slug %}">
                        <p>{{ tag.name }}</p>
                    </a>
                    {% if not forloop.last %}{% endif %}
                {% endfor %}
            </p>

            <p>Published {{ post.publictiondate }}</p>
            <p>{{ post.content|markdown|truncatewords_html:30 }}</p>
                    
        {% endfor %}
    </div>

    {% include "blog/posts/paginator.html" with page=posts %}

{% endblock content %}

blog/templates/blog/posts/form-post-comment.html
{% block content %}
<div style="color: red;">

     <h2>Add comment to post '{{ post.title }}'</h2>

     <form action=" {% url 'blog:post-comment' post.id %}" method='post'>
          {{ form.as_p }}
          {% csrf_token %}
          <p><input type="submit" value="'Add comment"></p>
     </form>
 </div>

{% endblock content %}

blog/templates/blog/posts/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

blog/templates/blog/posts/paginator.html
<div class="paginator" style='background-color: lightgrey;'>
    <span class="step-links">

        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number}}">Previous</a>
        {% endif %}

        <span class="current-page">
            Page {{ page.number }} of {{ page.paginator.num_pages }} pages
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number}}">Next</a>
        {% endif %}

    </span>
</div>

blog/templates/blog/posts/post-detail.html
{% extends "layout.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}

    <h1>{{ post.title }} {{ post.id }}</h1>
    <h3>{{ post.author }}</h3>
    {% if post.tags.all %}
        <h4>#{{ post.tags.all|join:' #' }}</h4>
    {% endif %}
    <h3>pbl {{ post.publictiondate }} upd{{ post.updatedate }}</h3>
    <p>{{ post.content|markdown }}</p>
    <p><a href="{% url 'blog:post-share' post.id %}">Send post</a></p>

    <div style="background: violet;">
        <h1>Similar posts</h1>
        {% for s_post in similar_posts %}
            <p><a href="{{ 'post.get_absolute_url' }}">{{ s_post.title }}</a></p>
        {% empty %}
            <h3>Thers no similar posts yet</h3>
        {% endfor %}
    </div>

    <div style="background: pink;">
        {% with comments.count as total_comments %}
            <h2>{{ total_comments }} Comments</h2>
        {% endwith %}

        {% include 'blog/posts/form-post-comment.html' %}

        {% for comment in comments %}
            <p>{{ comment.email}}, {{ comment.created }}, {{ comment.updated }}</p>
            <p>{{ comment.cmnt_txt }}</p>
        {% empty %}
            <h3>No comment yet</h3>
        {% endfor %}
    </div>
    

{% endblock content %}

blog/templates/blog/posts/post-share.html
{% extends "layout.html" %}

{% block title %}Share Post '{{ post.title }}'{% endblock title %}

{% block content %}

    {% if sent %}
         <h1>Sent = True </h1>
         <h1>Email send succesfully!</h1>
         <p>You send post '{{ post.title }}' pb.{{ post.publictiondate }} on adress {{ form.cleaned_data.recipient_email }}</p>
         <p>{{ post.content|truncatewords:10 }}</p>

    {% else %}
        <h1>Else sent = False </h1>
        <h1>Share post '{{ post.title }}' with your friends</h1>
        <form method="post">jhhhj
            {{ form.as_p }}
            {% for field in form %}
                {{ field.error }}
                {{ filed.label_tag }}
            {% csrf_token %}
            {% endfor %}
            <input type="submit" value="Sent">
        </form>
    {% endif %}          

{% endblock content %}

blog/templates/blog/posts/post-single-comment.html
{% extends "layout.html" %}

{% block title %}add comment{% endblock title %}

{% block content %}

    {% if comment  %}
        <h1>Your commment has been added</h1>              
        <p><a href="{{ post.get_absolute_url }}">Back to Post</a></p>

    {% else %}
        {% include 'blog/posts/form-post-comment.html'}
                
    {% endif %}

    {% include "blog/posts/paginator.html" with page=page_obj %}

{% endblock content %}

blog/templates/layout.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header></header>

    <main>
        <div id="content">{% block content %}{% endblock content %}</div>

        <div id="sidebar" style='color: blue; background-color: lightblue;'>
            <h1>Blog</h1>
            <p>{% number_of_all_published_posts %} Post on this blog</p>

                <h3>Latest posts</h3>
    {% show_latest_published_posts 3 %}

        </div>
    </main>

    <footer></footer>
    
</body>
</html>